const { _electron: electron } = require('playwright');
const { mkdtemp, mkdir, writeFile, rm } = require('node:fs/promises');
const { tmpdir } = require('node:os');
const path = require('node:path');
const assert = require('node:assert/strict');
const {fingerprintFolder}=require('../lib/fingerprint.cjs');

(async () => {
  const temp = await mkdtemp(path.join(tmpdir(), 'folio-ui-'));
  const root = path.join(temp, '.agents/skills');
  await mkdir(path.join(root, 'writing'), { recursive: true });
  await writeFile(path.join(root, 'writing', 'SKILL.md'), '---\nname: friendly-writing\ndescription: Write clear articles from your research notes.\n---\n# Friendly writing\nUse examples and revise.\n<script>window.bad=true</script>');
  const installed = path.join(root,'installed-sample');
  await mkdir(path.join(installed,'references'),{recursive:true});
  await writeFile(path.join(installed,'SKILL.md'),'---\nname: installed-sample\ndescription: Write a sample.\n---\nUse references.');
  await writeFile(path.join(installed,'references/example.md'),'Original reference.');
  const lockPath=path.join(temp,'.agents/.skill-lock.json');
  await writeFile(lockPath,JSON.stringify({version:3,skills:{'installed-sample':{source:'example/skills',sourceType:'github',skillFolderHash:(await fingerprintFolder(installed)).gitTree}}}));
  let app;
  try {
    app = await electron.launch({ args: [path.resolve(__dirname, '..')], env: { ...process.env, FOLIO_TEST: '1', FOLIO_TEST_HOME: temp, FOLIO_ROOTS: JSON.stringify([root]), FOLIO_DATA: path.join(temp, 'data') } });
    const page = await app.firstWindow();
    page.on('pageerror', error => console.error('Renderer error:', error.message));
    const installedBook=page.getByRole('button',{name:'Installed Sample',exact:true});
    await installedBook.click();
    await page.getByText('Verified against original',{exact:true}).waitFor();
    assert.equal(await page.getByLabel('My relationship to this skill').inputValue(),'auto');
    await page.getByLabel('My relationship to this skill').selectOption('created');
    await page.getByText('Skill type saved.',{exact:true}).waitFor();
    await page.keyboard.press('Escape');
    await writeFile(path.join(installed,'references/example.md'),'Edited reference.');
    await page.locator('#refresh-button').click();
    await page.getByText('Your shelves are up to date.',{exact:true}).waitFor();
    await installedBook.click();
    await page.getByText('Review changes',{exact:true}).waitFor();
    assert.equal(await page.getByLabel('My relationship to this skill').inputValue(),'created');
    await page.getByText('Your manual label takes precedence.',{exact:true}).waitFor();
    await page.getByLabel('My relationship to this skill').selectOption('auto');
    await page.getByText('Skill type saved.',{exact:true}).waitFor();
    await page.keyboard.press('Escape');
    await page.getByLabel('Filter by skill type').selectOption('installed');
    await page.getByText('No books on this shelf yet.',{exact:true}).waitFor();
    await page.getByLabel('Filter by skill type').selectOption('all');
    await page.getByRole('button', { name: /friendly writing/i }).first().click();
    assert.equal(await page.getByLabel('My relationship to this skill').inputValue(), 'auto');
    await page.getByLabel('Personal notes').fill('Draft survives classification.');
    await page.getByLabel('My relationship to this skill').selectOption('created');
    await page.getByText('Skill type saved.', { exact: true }).waitFor();
    assert.equal(await page.getByLabel('Personal notes').inputValue(), 'Draft survives classification.');
    await page.getByRole('button', { name: 'Favorite this skill' }).click();
    await page.getByLabel('Personal notes').fill('Keep examples short.');
    await page.getByRole('button', { name: 'Save notes' }).click();
    await page.getByRole('button', { name: 'Run reviews', exact: true }).click();
    await page.getByRole('button', { name: 'Add a review', exact: true }).click();
    await page.getByLabel('Review title').fill('Newsletter first draft');
    await page.getByLabel('What did you change?').fill('Asked for shorter paragraphs twice.');
    await page.getByLabel('Lesson for next time').fill('Specify paragraph length at the start.');
    await page.getByRole('button', { name: 'Save review', exact: true }).click();
    await page.getByText('Newsletter first draft', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'Instructions', exact: true }).click();
    await page.locator('.markdown-body h1').waitFor();
    assert.equal(await page.locator('.markdown-body h1').textContent(), 'Friendly writing');
    assert.equal(await page.locator('.markdown-body script').count(), 0);
    assert.equal(await page.evaluate(() => window.bad), undefined);
    await page.getByRole('button', {name:'Raw source',exact:true}).click();
    await page.locator('.source-pre').getByText('<script>window.bad=true</script>', { exact: false }).waitFor();
    assert.equal(await page.evaluate(() => window.bad), undefined);
    await page.getByRole('button', {name:'Rendered Markdown',exact:true}).click();
    await page.locator('.markdown-body h1').waitFor();
    await page.screenshot({path:path.resolve(__dirname,'../work/markdown-preview.png')});
    await page.keyboard.press('Escape');
    await page.reload();
    await page.getByRole('button', { name: 'Favorites', exact: true }).click();
    await page.getByRole('button', { name: /friendly writing/i }).first().click();
    assert.equal(await page.getByLabel('Personal notes').inputValue(), 'Keep examples short.');
    assert.equal(await page.getByLabel('My relationship to this skill').inputValue(), 'created');
    await page.getByRole('button', { name: 'Run reviews', exact: true }).click();
    await page.getByText('Newsletter first draft', { exact: true }).waitFor();
    await page.keyboard.press('Escape');
    await page.getByLabel('Filter by skill type').selectOption('installed');
    await page.getByText('No books on this shelf yet.', { exact: true }).waitFor();
    await page.getByLabel('Filter by skill type').selectOption('created');
    await page.getByRole('button', { name: /friendly writing/i }).first().click();
    await page.getByLabel('My relationship to this skill').selectOption('adapted');
    await page.getByText('Skill type saved.', { exact: true }).waitFor();
    await page.keyboard.press('Escape');
    await page.getByText('No books on this shelf yet.', { exact: true }).waitFor();
    await page.getByLabel('Filter by skill type').selectOption('adapted');
    await page.getByRole('button', { name: /friendly writing/i }).first().click();
    await page.getByLabel('My relationship to this skill').selectOption('installed');
    await page.getByText('Skill type saved.', { exact: true }).waitFor();
    await page.keyboard.press('Escape');
    await page.getByLabel('Filter by skill type').selectOption('installed');
    await page.getByRole('button', { name: /friendly writing/i }).first().waitFor();
    await page.reload();
    await page.getByRole('button', { name: /friendly writing/i }).first().click();
    assert.equal(await page.getByLabel('My relationship to this skill').inputValue(), 'installed');
    await page.keyboard.press('Escape');
    await page.getByPlaceholder('Find a skill or something you want to do…').fill('nonexistent');
    await page.getByText('No books on this shelf yet.', { exact: true }).waitFor();
    await page.getByPlaceholder('Find a skill or something you want to do…').fill('research');
    await page.getByRole('button', { name: /friendly writing/i }).first().waitFor();
    await page.screenshot({ path: path.resolve(__dirname, '../work/ui-test.png') });
    console.log('PASS: verified installation, changed references, manual override, automatic reset, Electron browsing, safe source rendering, favorites, notes, reviews, reload persistence, search and dismissal.');
  } finally {
    if (app) await app.close();
    await rm(temp, { recursive: true, force: true });
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
